### ISSUE TITLE
Stream from serial/COM port

### ISSUE THREAD

**Issue by CharlieKay2163** [M0r13n/pyais#106]
Is there a way to process the incoming stream of data from a serial/COM port similar to the TCP and UDP examples?

**Comment by M0r13n** [comment]
It’s definitely possible. But you need to implement the actual logic to read the raw messages from the serial port by yourself. The actual decoding can then be done by pyais. 

I don’t have a serial device, therefore I can not provide you with any sample code.

Did you take a look at pyserial? It looks promising: https://pyserial.readthedocs.io/en/latest/shortintro.html

**Comment by CharlieKay2163** [comment]
Thanks that seems to be working great.
