### ISSUE TITLE
AtoN codes do not match R0126 (A-126) Table 3 or M.1371-5 TABLE 74

### ISSUE THREAD

**Issue by AllNamesWereTakenIsNotAvailable** [M0r13n/pyais#109]
The pyais NavAid enum doesn't seem to align with the specs?

Specifically the AtoN Message 21 'Type of aids-to-navigation' field which pyais refers to as 'aid_type' for 'Leading Light Rear' was decoded as LEADING_LIGHT_FRONT.

The specs I am referring to are the latest "IALA Recommendation for The Use of the Automatic Identification System (AIS)"
and / or "Recommendation ITU-R M.1371-5 Technical characteristics for an automatic identification system using time division multiple access in the VHF maritime mobile frequency band".

Kind Regards

**Comment by M0r13n** [comment]
Hey @AllNamesWereTakenIsNotAvailable,

I took a look at [this PDF](https://www.iala-aism.org/product/r0126/) which seems to be the first one you mentioned and it seems that you are right. I updated the `NavAid` enum accordingly.

Thank you and have a great day
Leon
