### ISSUE TITLE
EpfdType Enum Missing InternalGNSS = 15

### ISSUE THREAD

**Issue by localhyphin** [M0r13n/pyais#121]
Please see ITU-R  M.585

0 = undefined (default)
1 = global positioning system (GPS)
2 = GNSS (GLONASS)
3 = combined GPS/GLONASS
4 = Loran-C
5 = Chayka
6 = integrated navigation system 
7 = surveyed
8 = Galileo
9-14 = not used
15 = internal GNSS

Kind Regards

**Comment by M0r13n** [comment]
@localhyphin Thank you. I just double checked and you are right. A fix is coming

**Comment by M0r13n** [comment]
Fixed in version 2.5.7
