### ISSUE TITLE
NoneFilter broken

### ISSUE THREAD

**Issue by webstey** [M0r13n/pyais#128]
NoneFilter was not filtering anything out for me. I changed 'False' to 'None' in this line and it works now. It looks like you were providing 'False' as the default to getattr, but then checking for 'None'. I may be missing some intended behaviour that my change breaks, but this worked for me.

https://github.com/M0r13n/pyais/blob/6ec596bb131966c6172e96401d786055fa80c82f/pyais/filter.py#L151

**Comment by M0r13n** [comment]
@webstey You are right. That's a rather dumb bug on my part. Thank you for bringing this up. :)

Fixed in version 2.6.1
