### ISSUE TITLE
Get Country Code

### ISSUE THREAD

**Issue by mnaranjo** [M0r13n/pyais#131]
Hello,

What would I have to do to obtain the 'country code' of a vessel? 

Thank you in advance

**Comment by M0r13n** [comment]
Hey @mnaranjo,

which country code are you referring to? As fair as I know, there are two types of _"country codes"_ in AIS messages:

- [Maritime Identification Digits](https://www.itu.int/en/ITU-R/terrestrial/fmd/Pages/mid.aspx): the first digits of the MMSI
- a subtype of message 6 (DAC = 200 FID = 21)

Neither is currently implemented in pyais. Support for the MID could easily be added. The latter is a rather rare type of message that is very specific and almost never occurs in real world scenarios. Therefore, I am a bit hesitant to add support for this subtype.

**Comment by mnaranjo** [comment]
Thank you very much for your help.

**Comment by M0r13n** [comment]
Hey @mnaranjo,

with the newest version of pyais you can get the country code and name:

```py
from pyais.util import get_country

# The first 3 digits of any MMSI number are indicative of the vessel's flag
country_code, country_name = get_country(249110000)
assert country_code, country_name == ('MT', 'Malta')
```
