### ISSUE TITLE
Decode raw payload data

### ISSUE THREAD

**Issue by xerpi** [M0r13n/pyais#143]
I have a GMSK demodulator that provides me with raw AIS payload data.
For example, from the following message:
```
!AIVDM,1,1,,A,86vcLMv0<f=fN3oJalUUu<bOJvL7,0*0D
```
What I get from the demodulator is:
```
20 6f ab 71 df 80 32 e3 6e 78 3d da a7 49 65 f4 ca 9f 6b e7 07
```
This payload has the following fields:
![image](https://github.com/M0r13n/pyais/assets/560596/e5b7d52f-9af1-4356-9648-5c634c8cf296)
(Message ID =  8, Source ID (MMSI) = 468376695)

I would like to use the  `pyais.messages.Payload` class (or equivalent) to pass the raw data bytes and be able to decode and get the fields of the message payload.

**Comment by xerpi** [comment]
I think we would need a constructor for `AISSentence` that takes a `bitarray`.
In a way, it would be like starting from here: https://github.com/M0r13n/pyais/blob/master/pyais/messages.py#L458

**Comment by M0r13n** [comment]
Hey @xerpi,

do I understand correctly: The demodulator provides the binary payload of the AIS message as a sequence of bytes? So no NMEA protocol, no multi part messages, no fragments, no checksum, etc? Also I suppose that there isn't any ASCII6 armour?

In this case your approach seems absolutely fine. The full code would then be:

```py
import bitarray

from pyais.messages import MSG_CLASS
from pyais.util import get_int

payload = b'\x20\x6f\xab\x71\xdf\x80\x32\xe3\x6e\x78\x3d\xda\xa7\x49\x65\xf4\xca\x9f\x6b\xe7\x07'
fill_bits = 0

bit_array = bitarray.bitarray()
bit_array.frombytes(payload)

ais_id: int = get_int(bit_array, 0, 6)
msg = MSG_CLASS[ais_id].from_bitarray(bit_array)

print(msg)
```

**Comment by xerpi** [comment]
Hi @M0r13n, thank you very much for your response.

My signal generator, given `!AIVDM,1,1,,A,86vcLMv0<f=fN3oJalUUu<bOJvL7,0*0D` as an input, produces a GMSK signal.
After demodulation, I notice that only `86vcLMv0<f=fN3oJalUUu<bOJvL7`, and not the other fields, forms part of the 168-bit long AIS payload  ("Data bits - Payload" in the image below, the bits between the preamble + start flag and the CRC + end flag) (more info [here](https://en.wikipedia.org/wiki/Automatic_identification_system#Message_format)).
![image](https://github.com/user-attachments/assets/d8c17323-4170-4667-b223-356cfa79d4a8)


Is this the standard behavior, or should the other fields (`!AIVDM,1,1,,A,` and `,0*0D`) also be sent?

**Comment by M0r13n** [comment]
Hi @xerpi,

That behavior is completely normal. Your demodulator yields the raw AIS payload. The additional fields you're referring to are part of an optional NMEA protocol layer that can encapsulate AIS payloads, functioning as a protocol within a protocol. However, this outer NMEA protocol layer is not required for the AIS message to be valid; the AIS payload itself is valid without it. The NMEA protocol is often used to encapsulate AIS data for standardized communication between marine electronic devices, but the core AIS messages themselves are valid and interpretable without this additional layer

**Comment by xerpi** [comment]
> Hi @xerpi,
> 
> That behavior is completely normal. Your demodulator yields the raw AIS payload. The additional fields you're referring to are part of an optional NMEA protocol layer that can encapsulate AIS payloads, functioning as a protocol within a protocol. However, this outer NMEA protocol layer is not required for the AIS message to be valid; the AIS payload itself is valid without it. The NMEA protocol is often used to encapsulate AIS data for standardized communication between marine electronic devices, but the core AIS messages themselves are valid and interpretable without this additional layer

Thank you for the detailed explanation!
Then, I'll use `MSG_CLASS[ais_id].from_bitarray(bit_array)` manually!
Thanks for this amazing library!
