### ISSUE TITLE
import SO_REUSEPORT in streams.py fails on Windows

### ISSUE THREAD

**Issue by poloturion54** [M0r13n/pyais#149]
SO_REUSEPORT isn't supported on Windows so streams cannot be imported or used.

Exception has occurred: ImportError
cannot import name 'SO_REUSEPORT' from 'socket' 

Introduced in 2.7.1

**Comment by M0r13n** [comment]
@poloturion54 Yes, you are right. Fixed with v2.7.2. Thank you for bringing this up!
