### ISSUE TITLE
TagBlock handle the 'g' tag (NMEA sentence grouping) as documented by NMEAv4 VDM/VDO Guide

### ISSUE THREAD

**Issue by Leila-Codes** [M0r13n/pyais#150]
As per this VDO/VDO decoding guide, and the NMEA specifications, there is a 'g' tag that hasn't yet been handled by this library. This 'g' tag represents a message grouping, such as when an AIVDM message is split into multiple parts. This allows the messages to be received out-of-order and grouped using these 'g' tags.

https://gpsd.gitlab.io/gpsd/AIVDM.html

![image](https://github.com/user-attachments/assets/ef1f6fba-a246-4e44-abe6-42a4f3beb0e5)

**Comment by M0r13n** [comment]
@Leila-Codes I merged your PR and renamed the attributes. Some checks failed due to missing type hints or wrong variable names. But I fixed them too.

I added support for basic grouping of sentences using a `TagBlockQueue` in #151

**Comment by M0r13n** [comment]
Closed with v2.8.0
