### ISSUE TITLE
Tracker output rate of turn shows up as enum name instead of float

### ISSUE THREAD

**Issue by SiggyF** [M0r13n/pyais#154]
When I write a turnrate to a file it shows up as "TurnRate.NO_TI_RIGHT" instead  of the expected float value. 
The code below generates lines like:
```
257002270,TurnRate.NO_TI_DEFAULT,0.0,5.316765,60.409667,199.1,511,,,,,,,,,,1729952133.733693,,,,5
```

This is due to the string representation of the `TurnRate` class. When I change `class TurnRate(float, Enum):` to `class TurnRate(float, ReprEnum):` it works as expected. This is also the approach that default enums such as [StrEnum](https://github.com/python/cpython/blob/c5b99f5c2c5347d66b9da362773969c531fb6c85/Lib/enum.py#L1352) (new in python3.11) take. 

I would be happy to submit a PR with the change of I change `class TurnRate(float, Enum):` to `class TurnRate(float, ReprEnum):` and similar constants, if it is considered a welcome change. 

```
#!/usr/bin/env python3
import base64
import csv
import dataclasses
import functools
import json
import time
import typing

import click
from tqdm.auto import tqdm

import pyais


def handle_track(track, writer):
    # called every time an AISTrack is created
    track_dict = dataclasses.asdict(track)
    writer.writerow(track_dict)


@click.command()
@click.argument("input", type=click.Path(exists=True))
@click.argument("output", type=click.File("w"))
@click.option("--ttl", type=float, default=30)
def convert(input, output, ttl):
    fieldnames = [field.name for field in dataclasses.fields(pyais.tracker.AISTrack)]

    writer = csv.DictWriter(output, fieldnames=fieldnames)
    writer.writeheader()
    with pyais.stream.FileReaderStream(input) as f:
        with pyais.AISTracker(ttl_in_seconds=ttl) as tracker:

            tracker.register_callback(
                pyais.tracker.AISTrackEvent.CREATED,
                functools.partial(handle_track, writer=writer),
            )
            tracker.register_callback(
                pyais.tracker.AISTrackEvent.UPDATED,
                functools.partial(handle_track, writer=writer),
            )
            tracker.register_callback(
                pyais.tracker.AISTrackEvent.DELETED,
                functools.partial(handle_track, writer=writer),
            )
            for i, msg in tqdm(enumerate(f)):
                tracker.update(msg)


if __name__ == "__main__":
    convert()

```

**Comment by M0r13n** [comment]
Hey @SiggyF,

`ReprEnum` was only added in [Python 3.11](https://docs.python.org/3/library/enum.html#enum.ReprEnum). Python 3.10 is supported until 2026 ([source](https://devguide.python.org/versions/)). Therefore, this is currently not an option. However, I am open to alternative approaches, as I consider your issues to be valid concerns—provided that the solution is reasonably elegant. I am thinking about overriding `__str__`:

```py
def __str__(self):
    return str(float(self))
```

But I need to consider any undesired side effects

**Comment by SiggyF** [comment]
Thanks for considering. That's a good point. 

I see some constants in the pyais (ManeuverIndicator, EpfdType) use IntEnum. Their behaviour changes from Enum to ReprEnum by upgrading to python>=3.11  (as the updated IntEnum also uses ReprEnum since). So any issues of changing to the repr behaviour will also occur if users upgrade their python version to >= 3.11, for the integer types. 

Note that the changed behaviour (since 3.11) is implemented by [reusing/copying](https://github.com/python/cpython/blob/67b270142d58b8f9a64f8ae2b84a195e7e49adda/Lib/enum.py#L626) the `__str__` method of the implemented type in the [`__new__`](https://github.com/python/cpython/blob/67b270142d58b8f9a64f8ae2b84a195e7e49adda/Lib/enum.py#L611) method of EnumType's. [`ReprEnum`](https://github.com/python/cpython/blob/67b270142d58b8f9a64f8ae2b84a195e7e49adda/Lib/enum.py#L1292) itself does not do anything, it's just a subclass of Enum.  The code (comments in enum in cpython) of cpython mentions that in some cases the pickle method would break. So that could be something to test for.

**Comment by M0r13n** [comment]
@SiggyF I created a PR adding a simple helper class `ReprEnum` to unify the behavior of `str()` and `repr()` across all enums (see #155). What do you think? This should meet your use case and is compatible with any version of python.

**Comment by SiggyF** [comment]
Thanks, looks good. Much appreciated!
