### ISSUE TITLE
Critical error in AIS stream processing: Partno 2 is not allowed!

### ISSUE THREAD

**Issue by Mobilitysensing** [M0r13n/pyais#156]
Hey,

I have a receiver running and once in a few days it crashes with "Critical error in AIS stream processing: Partno 2 is not allowed!"  .  Not sure how to handle this exception, below the code i'am using. The stream arises from AISHUB with seems filter the amount of messages so in this case is the first part missing ?

Regards
Sebastiaan

```
def process_ais_messages():
    """Main function to process AIS messages."""
    conn = connect_to_db()
    try:
       with TCPConnection('xx.xx.xx.xx', port=5000) as ais_stream:  
            for ais_msg in chain.filter(ais_stream):
                try:
                    process_ais_message(conn, ais_msg.asdict())
                except Exception as e:
                    print(f"Error decoding AIS message: {e}")
                except Exception as e:
                    print(f"Unexpected error processing AIS message: {e}")
    except Exception as e:
        print(f"Critical error in AIS stream processing: {e}")
    finally:
        conn.close()
        print("Database connection closed.")

```

**Comment by M0r13n** [comment]
Hey @Mobilitysensing,

this error occurs when attempting to decode a [type 24 message](https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_24_static_data_report). This message is one of the few where the interpretation varies depending on the `Part Number`:

> If the Part Number field is 0, the rest of the message is interpreted as a Part A; if it is 1, the rest of the message is interpreted as a Part B; values 2 and 3 are not allowed.

It seems that you are receiving invalid AIS messages. The error is therefore correct, as the pyais library does not know how to decode messages with an invalid Part Number. However, you are free to ignore any `UnknownPartNoException`. You could even catch all `AISBaseException` errors.
