### ISSUE TITLE
the pyais can't be installed, how to fix it?

### ISSUE THREAD

**Issue by zhangwanyu2020** [M0r13n/pyais#21]
hi , 
when i install the pyais , i got the error as follow:

"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

i have installed the Microsoft Visual C++ 14.0, it not works!

could you help me ?

thank you

**Comment by asuagar** [comment]
Hello,

I have the same problem.

Best regards,
Andrés

**Comment by M0r13n** [comment]
Hey, 

could you provide me a stacktrace and/or error message? My guess is, that is has something to do with the bit array module. This is written in C and has Python bindings. It might depend on some special headers that are not part of the default installation in Visualstudio. 

Kind regards, 
Leon

**Comment by M0r13n** [comment]
Added a note on how to install pyais with VS in the newest documentation.

**Comment by zhangwanyu2020** [comment]
Thanks very much,  I  have fixed this error by downloading Microsoft Visual C++ 14.0 again on another website,  it works. Maybe the first Microsoft Visual C++ doesn't work, but the second does.
