### ISSUE TITLE
Support for multiline AIS messages?

### ISSUE THREAD

**Issue by asuagar** [M0r13n/pyais#22]
Can multiline AIS messages be processed ? For example:

```
!AIVDM,2,1,5,A,53KQ<L01pv7ptTtN22059@DlU>2222222222220l1@D555V00:R0CRkp8888,0*41
!AIVDM,2,2,5,A,88888888880,2*21
```
Best regards,
Andrés

**Comment by asuagar** [comment]
Ok. I have just discovered it in the test files. It would be:

from pyais import NMEAMessage
msg = NMEAMessage.assemble_from_iterable(messages=[
            NMEAMessage(b"!AIVDM,2,1,5,A,53KQ<L01pv7ptTtN22059@DlU>2222222222220l1@D555V00:R0CRkp8888,0*41"),
            NMEAMessage(b"!AIVDM,2,2,5,A,88888888880,2*21")
        ]).decode().content

**Comment by M0r13n** [comment]
Hey, 

nice that you found a solution. :-)

Actually, I would love to refactor this functionality. The interface is quite bulky and not very pythonic. As soon as time allows, I will invest some work in there. 

Kind regards,
Leon

**Comment by M0r13n** [comment]
Updated the documentation with some examples on how to parse multiline messages.
