### ISSUE TITLE
How to decode invalid messages

### ISSUE THREAD

**Issue by asuagar** [M0r13n/pyais#28]
Hi,

I am dealing with a stream of AIS messages. Approximately 20 % are invalid. The library raises an exception and the message is not processed. For example, the following two:

```
!ABVDM,1,1,7,,B3seA8000?mPBpURDA?Q3wmQnDOJ,0*3C,1616655884
!AIVDM,1,1,,B,53ktrJ82>ia4=50<0020<5=@Dhv0t8T@u<0000001PV854Si0;mR@CPH13p0hDm1C3h0000,2*35
```
The first one has the channel empty and the second has more than 82 characters. I inserted both of them in [maritec](https://maritec.co.za/tools/aisvdmvdodecoding) and the messages were decoded. The "only problem" they had is an erroneous checksum. Is there a way to decode them with `pyais`? Using `NMEAMessage` function an error is raised and the message is not decoded. It could be possible to print warnings instead of raising exceptions?

Thank you so much for your work.

EDIT: other option could be to bypass the `validate_message` routine with an argument. Its default would be False.

**Comment by M0r13n** [comment]
Hey,

these are acutally two bugs.

1. Empty channels caused an error. See also #27. 
2. long messages were accidentally considered *too long*

Both issues have been fixed with #29 and are available with the newest version of pyais (`1.6.1`).

Update with:

`pip install -U pyais`

Kind regards,
Leon

**Comment by asuagar** [comment]
Hi,

I have used the last pyais version for processing several days of AIS messages without any problem. Thank you so much for your time and fast response to the problem.

Best regards,
Andrés

**Comment by M0r13n** [comment]
Hi,

nice to hear that! :-)

kind regards,
Leon
