### ISSUE TITLE
decode.py: decode_msg_23 should have 'shiptype' not 'ship_type'

### ISSUE THREAD

**Issue by brucebookman** [M0r13n/pyais#32]
There are two different keys for ship type.  Please only use one.

` 
decode_msg_5 ...
      'shiptype': ShipType(get_int_from_data(232, 240)),
decode_msg_19 .. 
      'shiptype': ShipType(get_int_from_data(232, 240)),
...
decode_msg_23 . . .
      'ship_type': ShipType(get_int_from_data(114, 122))
      
`

**Comment by M0r13n** [comment]
Done. Will be available in the next release
