### ISSUE TITLE
There is no way to gracefully break out of a stream

### ISSUE THREAD

**Issue by resistance22** [M0r13n/pyais#42]
Hello There
In UDPStream, TCPStream when you enter the loop there is no way to break out of the loop when there is **no message incoming** from UDPStream,TCPStream so using a UDPStream, TCPStream in a GUI application with the capability of starting and stopping the stream is impossible.

**Comment by M0r13n** [comment]
Hi @resistance22,

> when there is no message incoming from UDPStream,TCPStream

I think there is a misunderstanding here. The two classes mentioned are simple wrappers around the socket API. As such, the two interfaces behave exactly like normal sockets. This means that you, as the designer, will have to decide what the rules of etiquette are for a conversation.

pyais will only ask the kernel to create a new socket and then try to connect to the remote socket. The connection will initially be terminated only under the following conditions:

- the remote refuses to connect (wrong address, network error, etc)
- the remote closes the connection (reboot, shutdown, error, etc)
- the kernel closes the socket

It is important to note that the both classes provided by pyais are NOT closed if no data is transferred. This is normal behavior. For example, imagine that you are communicating with an AIS receiver that sends only a few messages. If the socket was simply closed when, for example, no messages were transmitted for 5 seconds, this would lead to errors.

But you can tell the socket to be closed explicitly:

```py
import socket

from pyais.stream import TCPStream

url = 'localhost'
port = 12346

with TCPStream(url, port=port) as stream:
   # tell the socket to be closed if no message was received for 5 seconds
    stream._fobj.settimeout(5)
    try:
        for msg in stream:
            print(msg.decode())
    except socket.timeout:
        print("No message received for 5 seconds")
```

Regardless, I am planning to revise the included socket API of pyais again to give more flexibility to the programmer.

**Comment by resistance22** [comment]
Dear @M0r13n Thanks for responding, I read the code and got a grasp of what's going on.
