### ISSUE TITLE
messages with missing sequential ID number or grater than 9

### ISSUE THREAD

**Issue by lalmiAhmed** [M0r13n/pyais#49]
I used this library to decode coming NMAE data from an AIS receiver, I don't really have that deep understanding of the working principle on NMEA messages but from what I found that the fourth number after the comma which is the sequential ID should be from 1 to 9
However on my case I faced two uncommon types where sometimes the sequential ID is 10, or just empty which will leads to "not supported type of messages" error.
As quick fix, on my code I added a condition to set the sequential ID to any number less than 9 in these cases, just to avoid the rising errors...because I notice that changing the "sequential ID" doesn't have any effect on the other message values (mmsi, type ...)
It seems not the correct way of solving this but it's a temporary solution...
I hope you consider my report, and If go wrong on any part please don't hesitate to contact me.

**Comment by M0r13n** [comment]
@lalmiAhmed You are right. This is something that is going to be fixed in v2. I am currently preparing a release of version 2. A lot of things will be fixed them. See also: https://github.com/M0r13n/pyais/issues/46

**Comment by M0r13n** [comment]
Closed with #46
