### ISSUE TITLE
ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by asuagar** [M0r13n/pyais#5]
I am dealing with the issue described in the title. I am using Google Colab for dealing with the data (Python 3.6.9). [This is the notebook](https://colab.research.google.com/drive/1OdeWFdaf7N-J4uPEZ3qLQip8voWE4XMr?usp=sharing) with the code. It appears some problem related with the typing library. Also, you can download the ais used in [this link](https://www.dropbox.com/s/kpp3u035tbgdahb/20201015T122532.txt?dl=0). 

Thank you so much for your work!

```python
from pyais import FileReaderStream

filename = '20201015T122532.txt'
for msg in FileReaderStream(filename):
    decoded_message = msg.decode()
    ais_content = decoded_message.content
```

```
/usr/local/lib/python3.6/dist-packages/pyais/util.py in <module>()
      1 from functools import partial, reduce
      2 from operator import xor
----> 3 from typing import OrderedDict, Sequence, Iterable
      4 
      5 from bitarray import bitarray

ImportError: cannot import name 'OrderedDict'
```

**Comment by M0r13n** [comment]
Thank you for this issue. I will dig into it at the weekend! 

Greetings,
Leon

**Comment by M0r13n** [comment]
I found the bug. I was importing from the wrong place. I changed:

```py
from typing imort OrderedDict
```

 to

```py
from collections import OrderedDict
```

This should fix your issue. Please tell me, if it works for you now!

Greetings

**Comment by asuagar** [comment]
Hello @M0r13n, thank you for your fast reply. I tried to run script again. The error has changed.

```python
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pyais/stream.py in _assemble_messages(self)
     34                 msg: NMEAMessage = NMEAMessage(line)
     35             except Exception as e:
---> 36                 raise ValueError(f'Failed to parse line "{line}"') from e
     37 
     38             # Be gentle and just skip invalid messages

ValueError: Failed to parse line "b'!SAVDM,1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68,1602757282\n'"
```

I think the problem is in the header of the line. "!SVADM," is adding an extrafield and, now, there are eight fields. I tried to avoid this error running the following code:

```python
from pyais.messages import NMEAMessage
line = '!SAVDM,1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68,1602757282\n'
NMEAMessage(line[7:])
```
However I get a new error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-9cb3f40e5084> in <module>()
----> 1 NMEAMessage(line[7:])

/usr/local/lib/python3.6/dist-packages/pyais/messages.py in __init__(self, raw)
     34 
     35         # An AIS NMEA message consists of seven, comma separated parts
---> 36         # values = raw.split(b",")
     37         values = raw.split(',')
     38 

TypeError: must be str or None, not bytes
```

I cannot understand where is the problem. Thank you by your kindly attention.

**Comment by M0r13n** [comment]
Hey,

you are correct. The lib only supports seven, comma separated values. You spotted the problem, but your approach was slightly off. If you do the following, it works:

```py
msg = NMEAMessage(b"!SAVDM,1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68")
assert msg.decode()
```

it works. You didn't split the string correctly:

```python
>>> line = '!SAVDM,1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68,1602757282\n'

# The following print the full line starting at the 7th character:
>>> line[7:]
'1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68,1602757282\n'

# Instead you first need to split the message into it's comma separated parts and after that reassemble it - without the last part:
>>> ','.join(line.split(',')[:-1])
'!SAVDM,1,1,0,A,H52M2B4TB1I0000<925BDI200300,0*68'
```

**Comment by asuagar** [comment]
Thank you so much for the explanation. The header of the line helps the parser. Now, the code works! The last field could be a checksum.

https://en.wikipedia.org/wiki/Automatic_identification_system#Message_format
