### ISSUE TITLE
Incorrect latitude and longitude

### ISSUE THREAD

**Issue by imbytecat** [M0r13n/pyais#51]
I found that the latitude and longitude were faulty and they swapped positions causing the error.

**Comment by M0r13n** [comment]
@imbytecat Thanks for your report. Could you provide some more details? Which message was affected? Examples to reproduce the error would be great.

**Comment by imbytecat** [comment]
Sorry, after I checked I found that this should be my misunderstanding.
This is a problem that happened when I was using the leaflect.js library.
String geo-points are "latitude, longitude", while array geo-points are [longitude, latitude]—the opposite order.

Your code is great and has helped me a lot!
