### ISSUE TITLE
in v2-alpha, MessageType21 payload includes shipname, which I think should just be name

### ISSUE THREAD

**Issue by dziban303** [M0r13n/pyais#52]
In messages.py:

```py
lass MessageType21(Payload):
    """
    Aid-to-Navigation Report
    Src: https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_21_aid_to_navigation_report
    """
....
    shipname = bit_field(120, str, default='')
```

I believe `shipname` should simply be `name`, which is what's listed in that [gitlab URL](https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_21_aid_to_navigation_report). 

I found this when testing a script I use which displays ship names my receiver is picking up. With ~v1.7 I would get only the shipnames, but with v2 in addition to ships I'd get A, B, C, 1, 2, etc., which are aids to navigation markers from type 21 messages.

**Comment by M0r13n** [comment]
@dziban303 

You are totally right. Thanks for bringing this up. Will be closed with #53
