### ISSUE TITLE
Messagetype27 lat/long should be signed

### ISSUE THREAD

**Issue by princeje** [M0r13n/pyais#65]
https://github.com/M0r13n/pyais/blob/21da419607a512256e3cfe9abc852738aa8c2599/pyais/messages.py#L1362-L1363

Discovered this while testing, seemed my numbers were off by half and never negative. Doing more testing today. I'm no ais expert but it seems like a bug.

**Comment by M0r13n** [comment]
Thanks for bringing this up. I checked this and it seems that your are right. I am going to fix this.
