### ISSUE TITLE
Decoding of Binary Payloads 

### ISSUE THREAD

**Issue by bsyzek** [M0r13n/pyais#7]
Thanks for the great module! Am I correct in understanding that the current code does not decode the binary payloads contained in AIS messages 6, 8, 25, and 26?

**Comment by M0r13n** [comment]
Hi, 

yes you are correct. The payload remains currently unchanged. I stumbled across some weird errors on some messages  when I tried to decode their payload. I then decided to leave it like that and never worked on it again. :-D


Tips and PR's improving that are welcome

**Comment by bsyzek** [comment]
Thanks for the quick response! It's definitely a tricky problem with so many different types of binary payloads. I might take a stab at it, and if successful I'll definitely submit a PR.

**Comment by M0r13n** [comment]
I would love to see it!
