### ISSUE TITLE
Incorect fill bits

### ISSUE THREAD

**Issue by DarekB62** [M0r13n/pyais#70]
There are errors in messages generated by pyais:

```
!AIVDM,2,1,,B,54Rofa@2;t484<o3340t8=V3400000000000000t2H0147?P06lm1D3R@h@0,2*45
!AIVDM,2,2,,B,00000000000,2*17
```
It should be:

```
!AIVDM,2,1,,B,54Rofa@2;t484<o3340t8=V3400000000000000t2H0147?P06jkk3hTVQAh,0*41
!AIVDM,2,2,,B,00000000000,2*17
```

_Number of fill bits_ on the first line is **...,2*45**. Proper value is **...,0*41**.
It is probably allways 0 on the first line of multiline messages.

**Comment by M0r13n** [comment]
@DarekB62 I think that this is already fixed with: https://github.com/M0r13n/pyais/pull/69

So you should be set by installing pyais version 2.1.2:

`pip install -U pyais`
