### ISSUE TITLE
A (debugging?) print statement is present in code

### ISSUE THREAD

**Issue by poljvd** [M0r13n/pyais#76]
The turnrate is being printed to the console every time it is present in a message. That should not be the case.

See the offending line here:
https://github.com/M0r13n/pyais/blob/56e42c6e336792c6ec92827be9834b2d1e85ed10/pyais/messages.py#L543

**Comment by M0r13n** [comment]
@poljvd 

Jep. That definitely should not be there.

**Comment by poljvd** [comment]
Thx for the quick fix. My console is clean again! :-)

**Comment by M0r13n** [comment]
Great! :laughing:
