### ISSUE TITLE
Urgent need 

### ISSUE THREAD

**Issue by MikeyJ4** [M0r13n/pyais#80]
Nice project...
Though am not a python dev but i strongly believe if you have reached the level of decoding ais that's shows a better understanding.

Well am a Java dev building an app related to ais... i have some questions i will like to ask can you privately please chat me up mikeshedrack88@gmail.com

**Comment by M0r13n** [comment]
@MikeyJ4 if you have any questions regard this module please ask them in this issue. :-)

**Comment by MikeyJ4** [comment]
It's not related to this module else i will open up

**Comment by M0r13n** [comment]
Then I will close this issue. 

I looked at the other issues in other repositories opened by you. It seems that you are looking for help with a school project. I don’t think that Issues in Github are a good idea for that. You should be asking your questions at Stackoverflow. 

For details about the AIS protocol I suggest looking at: https://gpsd.gitlab.io/gpsd/AIVDM.html

**Comment by MikeyJ4** [comment]
I have asked one of my  the questions on stackoverflow  as you suggested below is the link you can assist 

https://stackoverflow.com/questions/73625156/class-a-ais-transponder-nmea-message-logs
