### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by nonmeeboon** [M0r13n/pyais#90]
Hello,
I'm trying to use the decode function by following through the example code but end up getting the error saying "TypeError: 'dict' object is not callable".  This is code: 
decoded_s = decode("!AIVDM,1,1,,B,15NG6V0P01G?cFhE`R2IU?wn28R>,0*05")

May be it's something that I did not set up correctly. Can you please give me an advice on how to fix this issue? Thank you very much.

**Comment by ls-lheea-semrev** [comment]
Hi, 

You have to use a NMEAMessage object (see [README](https://github.com/M0r13n/pyais#readme))

`
import pyais 

message = pyais.NMEAMessage(b"!AIVDM,1,1,,B,15NG6V0P01G?cFhE`R2IU?wn28R>,0*05")
decoded = message.decode()
data = decoded.asdict()
`

**Comment by nonmeeboon** [comment]
Thank you! It's working great now.
